#model_sonnet="anthropic.claude-sonnet-4-20250514-v1:0"
#model_deepseek="openrouter/deepseek/deepseek-r1-0528"
files_agent:
  root_directory: "/home/petar/Documents"
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
calendar_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
task_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
github_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
  github_username: "PetarKalinovski"
books_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
movies_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
recommender_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
  substack_newsletters_file: "data/substack_newsletters.json"
  youtube_channels_file: "data/youtube_channels.json"
home_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"
big_boss_orchestrator_agent:
  model:
    model_id: "us.anthropic.claude-sonnet-4-20250514-v1:0"