#model_sonnet="anthropic.claude-sonnet-4-20250514-v1:0"
#model_deepseek="openrouter/deepseek/deepseek-r1-0528"
files_agent:
  root_directory: "/home/petar/Documents"
  model:
    model_id: "openrouter/openrouter/horizon-beta"
calendar_agent:
  model:
    model_id: "openrouter/openrouter/horizon-beta"
task_agent:
  model:
    model_id: "openrouter/openrouter/horizon-beta"
github_agent:
  model:
    model_id: "openrouter/openrouter/horizon-beta"
  github_username: "PetarKalinovski"
books_agent:
  model:
    model_id: "openrouter/mistralai/devstral-small"
movies_agent:
  model:
    model_id: "openrouter/mistralai/devstral-small"
recommender_agent:
  model:
    model_id: "openrouter/mistralai/devstral-small"
  substack_newsletters_file: "data/substack_newsletters.json"
  youtube_channels_file: "data/youtube_channels.json"
